#
# Makefile for misc devices that really don't fit anywhere else.
#
###include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += st7796s_hvga_dsi_cmd.o
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc



